server:
  port: 11301

spring:
  application:
    name: scabbard-admin
  profiles:
    active: '@spring.profiles.active@'
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/public/,classpath:/templates/