server:
  port: 11301
netty:
  server:
    port:
      websocket: 11303
      tcp: 11305
      udp: 11307

spring:
  application:
    name: scabbard-admin
  profiles:
    active: '@spring.profiles.active@'
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/public/,classpath:/templates/