mybatis:
  mapper-locations: classpath*:mapper/*.xml
#热部署生效
spring:
  devtools:
    restart:
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
      #classpath目录下的内容修改不重启
      exclude: /**
management:
  # 端点信息接口使用的端口，为了和主系统接口使用的端口进行分离
  server:
    servlet:
      context-path: /actuator
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'
swagger:
  show: true
