package org.acottage.scabbard.core.entity;

import java.io.Serializable;
import java.util.Date;

public class TestMyBatisGenerator extends TestMyBatisGeneratorKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_my_batis_generator.name
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_my_batis_generator.is_del
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    private Boolean del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_my_batis_generator.update_time
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_my_batis_generator.create_time
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_my_batis_generator
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_my_batis_generator.name
     *
     * @return the value of test_my_batis_generator.name
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_my_batis_generator.name
     *
     * @param name the value for test_my_batis_generator.name
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_my_batis_generator.is_del
     *
     * @return the value of test_my_batis_generator.is_del
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_my_batis_generator.is_del
     *
     * @param del the value for test_my_batis_generator.is_del
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    public void setDel(Boolean del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_my_batis_generator.update_time
     *
     * @return the value of test_my_batis_generator.update_time
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_my_batis_generator.update_time
     *
     * @param updateTime the value for test_my_batis_generator.update_time
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_my_batis_generator.create_time
     *
     * @return the value of test_my_batis_generator.create_time
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_my_batis_generator.create_time
     *
     * @param createTime the value for test_my_batis_generator.create_time
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}