package org.acottage.scabbard.core.entity;

import java.io.Serializable;

public class TestMyBatisGeneratorKey extends BaseDomain implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_my_batis_generator.id
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_my_batis_generator
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_my_batis_generator.id
     *
     * @return the value of test_my_batis_generator.id
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_my_batis_generator.id
     *
     * @param id the value for test_my_batis_generator.id
     *
     * @mbggenerated Mon Aug 24 12:21:43 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }
}