<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>scabbard</artifactId>
        <groupId>com.acottage</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>scabbard-admin</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.acottage</groupId>
            <artifactId>scabbard-core</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <!-- SpringBoot Web容器 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-thymeleaf -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
    </dependencies>

    <build>
        <!-- SpringBoot 打包插件 -->
        <plugins>
            <!--            <plugin>-->
            <!--                <groupId>org.springframework.boot</groupId>-->
            <!--                <artifactId>spring-boot-maven-plugin</artifactId>-->
            <!--                &lt;!&ndash; 忽略测试启动类 &ndash;&gt;-->
            <!--                <configuration>-->
            <!--                    <skip>true</skip>-->
            <!--                    &lt;!&ndash; devtools 热部署 &ndash;&gt;-->
            <!--                    <fork>true</fork>-->
            <!--                    <addResources>true</addResources>-->
            <!--                </configuration>-->
            <!--            </plugin>-->

            <!--            <plugin>-->
            <!--                <artifactId>maven-compiler-plugin</artifactId>-->
            <!--                <version>3.7.0</version>-->
            <!--                <configuration>-->
            <!--                    <source>11</source>-->
            <!--                    <target>11</target>-->
            <!--                    <encoding>UTF-8</encoding>-->
            <!--                </configuration>-->
            <!--            </plugin>-->
            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>2.2.4</version>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <!-- 使properties扩展到整个maven bulid 周期 Ref: https://github.com/ktoso/maven-git-commit-id-plugin/issues/280 -->
                    <injectAllReactorProjects>true</injectAllReactorProjects>
                    <dateFormat>yyyyMMddHHmmss</dateFormat>
                    <verbose>true</verbose>
                    <!-- 是否生 git.properties 属性文件 -->
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties
                    </generateGitPropertiesFilename>
                    <!--git描述配置,可选;由JGit提供实现; -->
                    <gitDescribe>
                        <!--是否生成描述属性 -->
                        <skip>false</skip>
                        <!--提交操作未发现tag时,仅打印提交操作ID, -->
                        <always>false</always>
                        <!--提交操作ID显式字符长度,最大值为:40;默认值:7; 0代表特殊意义;后面有解释; -->
                        <abbrev>10</abbrev>
                        <!--构建触发时,代码有修改时(即"dirty state"),添加指定后缀;默认值:""; -->
                        <dirty>-dirty</dirty>
                        <!--always print using the "tag-commits_from_tag-g_commit_id-maybe_dirty"
                            format, even if "on" a tag. The distance will always be 0 if you're "on"
                            the tag. -->
                        <forceLongFormat>false</forceLongFormat>
                    </gitDescribe>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>2.5.5</version>
                <configuration>
                    <appendAssemblyId>false</appendAssemblyId>
                    <descriptors>
                        <descriptor>doc/assembly/assembly.xml</descriptor>
                    </descriptors>
                    <finalName>
                        scabbard-${project.version}-${git.commit.time}-${git.commit.id.abbrev}
                    </finalName>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <!-- 指定配置文件路径 -->
        <resources>
            <resource>
                <directory>src/main/resources/config</directory>
                <filtering>true</filtering>
                <excludes>
                    <exclude>application*.yml</exclude>
                </excludes>
            </resource>
            <resource>
                <directory>src/main/resources/config</directory>
                <!-- 是否替换@xx@表示的maven properties属性值 -->
                <filtering>true</filtering>
                <includes>
                    <include>application.yml</include>
                    <include>application-${spring.profiles.active}.yml</include>
                    <include>application-core.yml</include>
                    <include>application-core-${spring.profiles.active}.yml</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <includes>
                    <include>**/*.xml</include>
                    <include>**/*.css</include>
                    <include>**/*.js</include>
                    <include>**/*.html</include>
                </includes>
            </resource>
        </resources>
    </build>
</project>