server:
  port: 11302

spring:
  application:
    name: scabbard-api
  profiles:
    active: '@spring.profiles.active@'
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/public/,classpath:/static/